### ISSUE TITLE
Data Caching when JSON is edited externally

### ISSUE THREAD

**Issue by NekaouMike** [PolygonDB/PolygonDB#8]
**Describe the bug**
Data showing up after being removed

**To Reproduce**
1.Append some data to the DB
2.Remove that data via a external file editor
3.Look for that data

**Expected behavior**
It should no longer be there but it shows up

**Screenshots**
<img width="358" alt="image" src="https://user-images.githubusercontent.com/36397097/217318950-57e0c933-1f3a-43e3-894b-df4df3137ec3.png">
<img width="148" alt="image" src="https://user-images.githubusercontent.com/36397097/217319032-1043a4fb-3bbe-451b-8897-0224ef0ce7da.png">

**Connection LIB**
PloyConJS

**Comment by JewishLewish** [comment]
So Polygon uses a thing called "Atomic Syncing" which allows the code to create a local save of the database because if you were to modify a database several times (or retrieve it) via websocket then there would be no point of constantly re-opening the database and using resources. 
When a database is accessed for the first time, it is sync'ed. For the second time (and more), it is re-used by the sync to preserve both memory and cpu. 

It is possible for me to work a "re-sync" terminal command for people who are manually modifying the database however if someone were to make a mistake and re-sync it. Then it can break everything.

**Comment by JewishLewish** [comment]
Closing Issue.

This problem is fixed the "re-sync" terminal system.

If you manually edited a json file then use terminal and type "re-sync name-of-database."
Moreover, if there is an error within the json file then it will refuse to re-sync.
